name: Azure WebApp CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: posnakegame-webapp
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish
