name: Deploy PoSnakeGame API to Azure App Service

on:
  push:
    branches:
      - master # Trigger deployment on push to master
    paths:
      - 'PoSnakeGame.Api/**' # Only trigger if API project changes
      - '.github/workflows/deploy-api.yml' # Or if this workflow changes

env:
  AZURE_WEBAPP_NAME: posnakegame-api   # Name of the Azure App Service
  AZURE_RESOURCE_GROUP: PoSnakeGame   # Name of the resource group
  DOTNET_VERSION: '8.0.x'           # .NET version
  PROJECT_PATH: 'PoSnakeGame.Api/PoSnakeGame.Api.csproj' # Path to the API project

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Requires AZURE_CREDENTIALS secret

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './publish' # Deploy the published output

    - name: Logout from Azure
      run: |
        az logout
        az cache purge
        az account clear
