name: Build and deploy .NET Core application to Web App posnakegame-staticwebapp
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - master
  push:
    branches:
    - master
env:
  AZURE_STATIC_WEBAPP_NAME: posnakegame-staticwebapp
  APP_DIRECTORY: PoSnakeGame.Wa
  API_DIRECTORY: PoSnakeGame.Functions
  OUTPUT: wwwroot
  DEPLOYMENT_ENVIRONMENT: production

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.posnakegame_staticwebapp_SPN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: upload
        deployment_environment: ${{ env.DEPLOYMENT_ENVIRONMENT }}
        app_location: ${{ env.APP_DIRECTORY }}
        # api_location: ${{ env.API_DIRECTORY }} # Remove API location - deploying API separately
        output_location: ${{ env.OUTPUT }}
        app_build_command: dotnet publish -c Release -o publish
        # api_build_command: dotnet publish -c Release -o publish # Remove API build command
        
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Close Pull Request Job
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.posnakegame_staticwebapp_SPN }}
        action: close
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        app_location: ${{ env.APP_DIRECTORY }} # Add app_location back for close action
